export const codigo = {
  100: "Mensaje Enviado Correctamente",
  101: "API User no incluido en la cadena original",
  102: "API Password no incluido en la cadena original",
  103: "Texto del SMS no incluido en la cadena original",
  104: "Número celular del SMS no incluido en la cadena original.",
  105: "Tamaño de mensaje excedido",
  109: "Error En red",
  110: "Error En red",
  120: "Mascara No Permitida",
  200: "Error de Sistema",
  201: "Usuario o password incorrectos.",
  202: "IP no permitida para esta acción",
  204: "Numero de mensajes permitidos superado",
  205: "Trafico no permitido",
  254: "Error, No fue posible enviar el mensaje por ningún proveedor.",
  300: "Error Interno en el Servidor SMS",
  302: "messageID no incluido",
  305: "Error de Sistema",
  306: "Error de Sistema",
  307: "Número fijo o incorrecto",
  309: "Error en serie numérica",
  310: "Intermitencia en el servicio",
};
